In [44]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random
def regression(X,Y,k):
    
    real_X = np.vstack(X for x in range(k))
    len_X = len(X)
    for i in range(len_X):
        for kk in range(k):
            real_X[kk, i-1] = (X[i-1]**(kk))
    
    XTX = real_X.dot(real_X.T)
    XTY = real_X.dot(Y)
    w = np.linalg.inv(XTX).dot(XTY)
    print(XTX)
    print(XTY)
    print(w)


In [47]:
a = [1 ,2, 3, 4]
b = [3, 2, 0, 5]
regression(a,b,4)

[[   4   10   30  100]
 [  10   30  100  354]
 [  30  100  354 1300]
 [ 100  354 1300 4890]]
[ 10  27  91 339]
[-5.         15.16666667 -8.5         1.33333333]


In [ ]:
def evaluate_reg(w,X,Y):
    